spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/heroes?allowPublicKeyRetrieval=true&sslMode=DISABLED&rewriteBatchedStatements=true}
    username: ${DB_USERNAME:heroes}
    password: ${DB_PASSWORD:heroes_user}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    to: ${MAIL_TO:}
    from: ${MAIL_FROM:}
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    ssl:
      enabled: true
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          timeout: 2000
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8090}
